### ISSUE TITLE
Activity Duration not logged after having called Activity.Stop()

### ISSUE THREAD

**Issue by kabua** [NLog/NLog.DiagnosticSource#31] opened 2021-03-10 22:57 UTC
Version: 1.0.1

Note the StartTimeUtc format works just fine but there are two bugs with Duration.

1. The duration is always zero
2. The format for the duration doesn't work.

### Layout
`"StartTimeUtc=${activity:StartTimeUtc:format=yyyy-MM-dd HH\:mm\:ss.fff}|Duration=${activity:Duration:format=HH\:mm\:ss.fff}"`

### Output
`StartTimeUtc=2021-03-10 23:04:47.532|Duration=`

### Expected
`StartTimeUtc=2021-03-10 23:04:47.532|Duration=00:00:00.000`

**Comment by snakefoot** [comment] 2021-03-10 23:02
Did you remember to start the activity?

```c#
System.Diagnostics.Activity.Current = new System.Diagnostics.Activity("MyOperation").Start();
```

If you can write an unit-test along with a code-fix, then pull-requests are very welcome

**Comment by kabua** [comment] 2021-03-10 23:13
Yes. Here's a code snippet: 


            using(var activity = new Activity("Main").Start())
            {
                RunProcess();  // Thread.Sleep(3 sec)
                activity.Stop();

                var duration = activity.Duration;
                var s = duration.ToString("G");    // => 0:00:00:03.0520680
            }

But log shows:
`StartTimeUtc=2021-03-10 23:11:17.969|Duration=`

**Comment by snakefoot** [comment] 2021-03-10 23:33
Cannot see where Logging occurs in that code-example

**Comment by snakefoot** [comment] 2021-03-10 23:51
Found it not very intutive that Activity.Duration returned zero-duration until stopped. So created ver. 1.0.2:

https://www.nuget.org/packages/NLog.DiagnosticSource/1.0.2

**Comment by kabua** [comment] 2021-03-10 23:53
I've pulled the code and created a unit-test, but duration was null, so I tried getting the StartTimeUtc property, also null. So, I added several asserts. Turns out that `Activity.Current` is set to `null` once `activity.Stop()` is called. 

Here's my current unit-test:

        [Fact]
        public void TestDuration()
        {
            LogManager.ThrowExceptions = true;

            var activity = new System.Diagnostics.Activity(null).Start();
            Assert.NotNull(Activity.Current);

            Thread.Sleep(TimeSpan.FromSeconds(3));
            Assert.NotNull(Activity.Current);

            activity.Stop();
            Assert.NotNull(Activity.Current);    // <-------------------------- Test fails here

            var logEvent = LogEventInfo.CreateNullEvent();

            var layoutRenderer = new ActivityTraceLayoutRenderer
            {
                Property = ActivityTraceProperty.StartTimeUtc,
                //Format = "hh:mm:ss.ffff"
            };

            var result = layoutRenderer.Render(logEvent);
        }

Thus none of the values in the layoutRenderer will render correct. 

This would also explain why when I log the `OperationName` I see the parent name and not the current operational name.

I think, some how, you will need to capture the current activity at creation time and not at logging time.

**Comment by snakefoot** [comment] 2021-03-10 23:55
Instead of calling `activity.Stop();` then do this:

```c#
activity.SetEndTime(DateTime.UtcNow);

// Do some final logging

activity.Stop();   // Resets activity
```

**Comment by kabua** [comment] 2021-03-11 00:14
I can try it to see if I can get the Duration property working properly in the unit-test and this might be a temporary 'work-a-round' but I don't expect developers to think (or use it) that way in the long term.

Also, this bring up another question; does NLog have a pattern or a process where by state can be captured before logging? For example:

1. function Begin/End logging
2. stopwatch start/stop logging (which may be replaced with Activity now)
3. capturing the callsite before the first `await` call is made.

I'm asking because we have written a wrapper around NLog to support these types of logging scenarios and was wondering if there was built-in support for this already.

**Comment by kabua** [comment] 2021-03-11 00:20
Okay, using `activity.SetEndTime(DateTime.UtcNow);` worked... sort of.

If I don't set the `Format` property it works. However, I can't use `Format = "hh:mm:ss.ffff"` otherwise I get a `FormatException`, turns out that Microsoft isn't consistent in their format strings between `DateTime` and `TimeSpan`. TimeSpan requires that ":" and "." are escaped. Therefore, the following works:

`Format = @"hh\:mm\:ss\.ffff"

Now, results equals "00:00:03.0269"

**Comment by kabua** [comment] 2021-03-11 00:31
Thanks for producing 1.0.2 so quickly, however, I think we need to update the `GetDuration()` function, before line 141 with something like:

`format = format.Replace(":", @"\:").Replace(".", @"\.");`

or with a regex expression.

Test example:

            var format = @"hh:mm:ss.ffff";
            format = format.Replace(":", @"\:").Replace(".", @"\.");

            var layoutRenderer = new ActivityTraceLayoutRenderer
            {
                Property = ActivityTraceProperty.Duration,
                Format = format
            };

            var result = layoutRenderer.Render(logEvent);


works.

**Comment by kabua** [comment] 2021-03-11 00:45
Using nlog.config, how do I pass an escape character into the forma string?

For example this doesn't work: `Duration=${activity:Duration:format=hh\\:mm\\:ss\\.fff}`

I get a `TypeInitializationException: Invalid enumeration value 'mm\'.`

**Comment by snakefoot** [comment] 2021-03-11 07:04
Yes it is a little confusing the NLog-LayoutRenderer parser because `:` has special meaning:

> @"hh\\:mm\\:ss.ffff"

Should match this in NLog.config:

> ${activity:Duration:format=hh\\:mm\\:ss.fff}

See also `Format`-option in https://github.com/NLog/NLog/wiki/Date-Layout-Renderer#rendering-options (handling colon)

**Comment by snakefoot** [comment] 2021-03-11 07:21
> - function Begin/End logging

No not that performs logging on enter/exit, or only logs exit when slow duration.

> - stopwatch start/stop logging (which may be replaced with Activity now)

If performance is important then Activity with DateTime.UtcNow will be slow. Then StopWatch is faster. NLog has some timing logic that works together with [NDLC](https://github.com/NLog/NLog/wiki/NDLC-Layout-Renderer) using `${ndlctiming}`
 
> - capturing the callsite before the first await call is made.

NLog has something called [${callsite}](https://github.com/NLog/NLog/wiki/Callsite-layout-renderer) that is extremely slow. And not the best support for caller-member-attributes. This will be improved with NLog 5.0, so it can be used in a "fast" mode.

**Comment by kabua** [comment] 2021-03-11 18:05
> Yes it is a little confusing the NLog-LayoutRenderer parser because `:` has special meaning (means start of new option):
> 
> > Format = @"hh\\:mm\\:ss\\.ffff"
> 
> Should match this in NLog.config:
> 
> > ${activity:Duration:format=hh\\:mm\\:ss\\.fff}
> 
> See also `Format`-option in https://github.com/NLog/NLog/wiki/Date-Layout-Renderer#rendering-options (escaping colon)

As stated above, this doesn't work because NLog will strip out the "\\"s and the formater will only see "hh:mm:ss.fff" but it needs to see "hh\\:mm\\:ss\\.fff" but if we try to escape the backslash (as in: "hh\\\\:mm\\\\:ss") then we get an error due to "mm\\"

**Comment by snakefoot** [comment] 2021-03-11 18:29
Can you provide an unit-test that reproduces the issue?

**Comment by snakefoot** [comment] 2021-03-11 19:32
Yes I now see that I have given wrong advice. It is not 1 or 2 or 4, but 3 is the magic number.

> Format = @"hh\\\\\\:mm\\\\\\:ss\\\\.ffff"

Should match this in NLog.config:

> ${activity:Duration:format=hh\\\\\\:mm\\\\\\:ss\\\\.fff}

So 2 escapes `\\` to generate an actual escape, and a bonus-escape `\` for the colon (Because of layout-parser). Thus `\\\:`

The dot requires no bonus-escape. Thus `\\.`

**Comment by snakefoot** [comment] 2021-03-17 20:56
Closing the issue as resolved

**Closed by snakefoot** 2021-03-17 20:56 UTC
Labels: question
